In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[:5]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [16]:
slice_of_arr[:] = 100

In [17]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [18]:
 arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
accr_copy[:] = 2

NameError: name 'accr_copy' is not defined

In [22]:
arr_copy[:] = 2

In [23]:
arr_copy

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [25]:
arr_2d = np.array([[5,10,15],[20, 25, 30], [35, 40, 45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d.shape

(3, 3)

In [28]:
arr_2d[0]

array([ 5, 10, 15])

In [29]:
arr_2d[2]

array([35, 40, 45])

In [30]:
arr_2d[2, 1]

40

In [31]:
arr_2d[1,1]

25

In [32]:
arr_2d[1:, 1:]

array([[25, 30],
       [40, 45]])

In [33]:
arr = np.arange(0, 11)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 4


array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [36]:
bool_arr = arr>4

In [37]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [38]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])