In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4]

In [3]:
np.array(mylist)

array([1, 2, 3, 4])

In [4]:
nested_list = [[1,2],[3,4],[5,6]]

In [5]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [6]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.arange(0, 20, 2, dtype=int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.zeros((3,))

array([0., 0., 0.])

In [11]:
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [12]:
np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'

In [13]:
np.ones((2, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(3,2)

array([[0.28048796, 0.26154184],
       [0.71977673, 0.09820476],
       [0.99345041, 0.84597597]])

In [17]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [18]:
np.random.randint(1)

0

In [19]:
np.random.randint(2, size=20)

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ran_arr = np.random.randint(0, 50, 10)

In [23]:
ran_arr

array([20, 32, 11, 21, 43, 24, 48, 26, 41, 27])

In [24]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ran_arr.max()

48

In [26]:
ran_arr.min()

11

In [27]:
ran_arr.argmax()

6

In [28]:
ran_arr.argmin()

2